<<<<<<< HEAD
# Tipo de conexion del sistema: local o en la nube
system:
  connection_type: local   # opciones: local / cloud
  notification_channel: "slack"  # opciones: email / slack / telegram / none

# Ubicaci贸n de la base de datos local
local_database:
  path: "data/db/fake_db.sqlite"

# Ubicaci贸n de la base de conocimiento
knowledge_base:
=======
# Tipo de conexion del sistema: local o en la nube
system:
  connection_type: local   # opciones: local / cloud
  notification_channel: "slack"  # opciones: email / slack / telegram / none

# Ubicaci贸n de la base de datos local
local_database:
  path: "data/db/fake_db.sqlite"

# Ubicaci贸n de la base de conocimiento
knowledge_base:
>>>>>>> d66169c081f129a63f3e88518ef7186fbd60c3c4
  path: "src/knowledge/knowledge.json"